name: deploy

on:
  push:
    branches: [next]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      # - name: Use Node.js v14.x
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: '14.x'

      - name: Install
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: .vuepress/dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # force_update: true
          # debug: true
